const text=    `


ALUMNI SPOTLIGHT: FROM WARSAW TO NEW YORK, AVA PACCHIANA ’18 HOLDS COMMUNITIES TOGETHER
By Dylan Howlett

Ava Pacchiana ’18 had time on her hands, and an inclination to use it. “I wanted to do something different,” Pacchiana said. She had just graduated from Vanderbilt University, where she interned with the ACLU and the Tennessee General Assembly — the latter of which passed a resolution, in 2021, to recognize her “exemplary service as a legislative intern.” She had also been accepted to Harvard Law School by way of its junior deferral program, which allows students to delay their enrollment by two years. Pacchiana just needed to define, exactly, that something. “I didn’t know what that was going to look like,” she said.

Pacchiana soon connected with Jonathan Mills, a Chapel Hill native who had spent part of his career in Poland before moving back to North Carolina. It was February 2022, and Russia had launched its ground invasion of Ukraine. The growing conflict displaced millions of Ukrainians who were crossing the border between Poland and Ukraine in staggering numbers. The population of Warsaw, the Polish capital, grew by 15%. Estimates suggest the number of Ukrainians crossing into Poland has now exceeded 15 million.

Amid the despair, Mills couldn’t help but think of Poland. “He said, ‘What can we do to help Ukraine and the Ukrainian refugees here?’” Pacchiana recalled. The answer was indelible, both for Ukrainians and for Pacchiana.

Mills partnered with a local Polish nonprofit to found Spynka, an organization that employs and trains Ukrainian women as educators within early childhood education programs. The purpose was twofold: give refugees meaningful employment, and give their children a safe place to learn and grow. The organization’s mission was evident in its name: Spynka means “spine” in Ukrainian and “paperclip” in Polish — “the idea behind it being that it’s holding the community up and together,” Pacchiana said.


She moved to Warsaw in June 2022 and spent 10 months with Fundacja Rozwoju Dzieci (Foundation for Child Development), the nongovernmental organization that implemented Spynka. Pacchiana was one of only a few staff members who didn’t speak Polish or Ukrainian. She had never written grants before, but she became the organization’s lead grant writer and raised $11 million. Spynka had opened 23 early childhood programs when Pacchiana arrived. By the time she left, in June 2023, the organization had expanded to 75 programs. “It wasn’t always pretty, but I made it,” Pacchiana said, “and I’m really proud of what I did on the other side.”

That other side, understandably, could have been a year of respite before she started law school. Instead, Pacchiana walked all 500 miles — and an extra 100, for good measure — of the famed Camino de Santiago in Spain. She’s now in the midst of a year of public service at the Innocence Project, the New York-based nonprofit dedicated to overturning, and preventing, wrongful convictions. It represents a continuation of her work at Vanderbilt, where Pacchiana served as vice president of the Vanderbilt Prison Project; co-led a local clemency campaign; organized a community-based Court Watch program; and planned weekly dinners attended by Vanderbilt students and the previously incarcerated. “It’s very intense and heartbreaking,” she said, “but I feel like it’s the best work you can do, really.”

Pacchiana spoke with the Marketing & Communications team in October for an extended conversation about that best work: with Spynka, with the Innocence Project and on the trails of the Camino. All of it, she says, has indeed amounted to something different — and endlessly rewarding.

This conversation has been lightly edited for clarity and brevity.

DA: I’m sure you’ve encountered a fair number of adults who have given up and said, “The problems are too big, the system is too broken, there’s nothing you can do.” What was it about criminal justice reform that compelled you to take on such an intractable challenge?

Pacchiana: One thing that I want to say in response to thinking about the older generation and their attitudes toward it is that the future is in the hands of our generation and younger people. We’re the ones with the resilience and motivation and inspiration to actually make change. Some people are like, “Oh, you’re 23. You’re so young to be doing all of this.” And I’m like, “This is the time that we should be doing this.” In 20 years, who knows what I’m going to be? Life gets in the way, but to be able to do this work now, it’s the time — and we have the energy to actually make change. With regards to criminal justice, I’m very much a people person. At Durham Academy, I took a class that Mr. Ulku-Steiner (Head of School Michael Ulku-Steiner) and Mr. Hark (former Associate Head of School Lee Hark) were leading together. It was called “Mission-Driven Life,” and it was the first year they did it. It was the coolest class. That was probably my highlight from Durham Academy. The class was basically designed to have you create a mission statement for your purpose in this world. What are you trying to do? And the thing that I always came back to was connection, and connecting with other people. I think that the whole idea behind the criminal justice movement right now is that everybody has a story, and your story — and who you are — is so much bigger than the worst thing you’ve ever done. That idea just spoke to me so instantly. That’s something that I believe in my day-to-day life. And that’s what our criminal justice system needs to shift toward, this new perspective of how we see each other. I think it does connect back to Mission-Driven Life and the work that we were doing in that class, and the desire to connect with people and hear people’s stories.

DA: I think you would have been forgiven had you said, “I’ve gotten this deferral for law school. I’m going to sit on a beach for two years.” But you chose to go to Eastern Europe during a particularly volatile time. Beyond the impact and the scope of all the work that you did, what did you learn about yourself during those 10 months in Poland?

Pacchiana: I learned how much you learn outside of the classroom. There was nothing that Durham Academy or Vanderbilt could have done to prepare me for the real-life education that I got being there and learning how to operate in an organization where almost everyone doesn’t speak the same language as I do. I’m completely alone in a new country, the culture is completely different, there’s a war happening 100 miles away. The thing that I learned about myself is I could do hard things. That was really a big takeaway for me.

DA: The Innocence Project must be a little more familiar for you given your extensive work in the criminal justice space while you were at Vanderbilt. What is your day-to-day role with the organization?

Pacchiana: The Innocence Project takes cases for people with claims of innocence where there’s an opportunity for DNA testing to prove them innocent. I’m working directly under our attorneys on the post-conviction litigation team. These are the attorneys who are working directly with our clients, litigating, doing the DNA testing, basically trying to exonerate them. I’m working on a couple of different projects right now. In one case, I’m in an investigative role looking into an alternate suspect in the crime. On another case, we were not successful in court, so I’m working on pulling together parole packets for our client, basically supporting him once he goes in front of the parole board after 50 years of being incarcerated. I’m doing a little bit of departmental stuff, working on a database of all the exonerations. We’re trying to make sure that’s comprehensive because it’s a work in progress. It’s been surprisingly niche projects depending on the case, learning a lot of random things that somehow pertain to the case we’re working on.


DA: What’s the randomest yet most noteworthy thing you’ve learned in these cases?

Pacchiana: I guess I’ve learned a lot about police corruption. I wish I were kidding, but working on these cases, the things you see are crazy. There’s actually an evidentiary hearing that I’m going to in January for a case. Her name is Sandra Hemme, and she’s based in Missouri. She’s been incarcerated for 42 years now for a murder she didn’t commit. (Editor’s Note: Hemme is the longest-known wrongly incarcerated woman in the U.S., according to the Innocence Project.) I’m learning all about false confessions and the ways that police interrogations lead to people confessing to things they didn’t do and spend their entire life in prison. That’s been shocking. I knew about it before, but actually working on it and getting to know the people and the circumstances behind what led them there, it’s astonishing in many ways. Honestly, a lot of the work is like that. Very similar to Poland — and in some ways, Poland prepared me for this — but it’s one of the most heartbreaking and rewarding jobs at the same time. We talked to Sandy Hemme yesterday, and she’s been sitting in prison ever since she was 17 and falsely accused of a murder while she was receiving tranquilizing medication. She was completely incapacitated; she should not have been giving a confession. You see the worst of the worst — and also in my first week here, we had three exonerations. We were able to do DNA testing and prove that it wasn’t them. They were released, they cleared their name and they were given their life back.


DA: After your 10 months in Warsaw, you said you did some “walking in Spain,” which is quite the understatement: You completed the Camino de Santiago, the famed 500-mile pilgrimage across Spain. What was that like?

Pacchiana: I’m proud of it, and it’s not a conventional achievement. It doesn’t sound as good on paper. But after I was in Poland, I decided that I needed some self-care time. I turned to my bucket list and decided to walk Camino de Santiago by myself for five weeks. I started in Saint-Jean in France, just over the border, and walked over 600 miles to Santiago and actually passed Santiago to the coast so I could say I made it across the entire country. That was the coolest thing ever. I was carrying everything on my back, I was walking by myself, I was meeting people from around the world. It was awesome. Everyone who has an opportunity to do something like that, I’m like, “Go! Go! Go!” The Camino is amazing. That was me in my happy place, I think.

DA: Would you have anticipated doing this work — and living this life — when you were a student at DA?

Pacchiana: I very much flew under the radar at Durham Academy. If you would have asked me then where I would be now, I never would have thought this. I know there are other kids who have been at Durham Academy forever and are going to get a ton of recognition, and I was never one of those kids. I didn’t feel like I was thriving at Durham Academy. But on the other side, I’m better because of it, you know? I have a couple of close friends from Durham Academy. We weren’t the cool people necessarily, but looking at us now — one of my best friends is a teacher now, and I’m doing my work — we get together now and we’re like, “Wow, we’re killing it.”
`

export default text